### ISSUE TITLE
Concurrent Modification exception

### ISSUE THREAD

**Issue by ghost** [decentralised-home-automation-protocol/DHAP-Android#7]
Occasionally, the app will crash from a concurrent modification exception in UdpPacketSender. This is most likely due to a separate thread removing or adding itself from the PacketListeners list while the UdpPacketSender is notifying the listeners of a new packet.

**Comment by ghost** [comment]
2019-09-08 19:58:31.523 4277-4330/me.aidengaripoli.dhapexample E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: me.aidengaripoli.dhapexample, PID: 4277
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at me.aidengaripoli.dhap.UdpPacketSender.lambda$listenForPackets$1$UdpPacketSender(UdpPacketSender.java:117)
        at me.aidengaripoli.dhap.-$$Lambda$UdpPacketSender$7l4a6zkyGFG2TOtJ1Cki0Jl7UCc.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
